title: 32. TaCoS
description: > # this means to ignore newlines until "baseurl:"
  32. TaCoS Conference in Düsseldorf
baseurl: "" # the subpath of your site, e.g. /blog
url: "tacosconference.github.io/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Twitter
  link: "https://twitter.com/tacosconference"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

#include: ['_2016_pages', '_2017_pages']

include: ['_2023_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: facebook
  #  url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com/tacosconference

# Build settings
markdown: kramdown
permalink: pretty
